# Generated by Django 5.0.6 on 2024-05-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bachelor_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
