# Generated by Django 5.0.6 on 2024-06-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bachelor_projects', '0002_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='linkedin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='phone',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
